package edts.android.composedemo.ui.screen

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.tooling.preview.PreviewParameter
import androidx.compose.ui.unit.dp
import edts.android.composedemo.constants.Destinations
import edts.android.composedemo.constants.ThemeMode
import edts.android.composedemo.ui.component.DemoScaffoldComp
import edts.android.composedemo.utils.StringUtils
import edts.android.composedemo.utils.preview.PreviewWrapperComp
import edts.android.composedemo.utils.preview.ThemePreviewProvider

/**
 * Uncomment after you successfully implement relay
 * because the component below is generated by it.
 * Here's how:
 * 1. Install the Relay Plugin
 * 2. Join this figma https://www.figma.com/design/5KimWIkBkpoz8zoLNznWTK/Untitled?node-id=0-1&t=cl2cyXGs24RBEuO0-1
 * 3. Generate figma token in figma settings -> Security -> Generate token
 * 4. Use the token on Relay Plugin
 * 5. Android Studio File -> New -> Import UI Package
 * 6. Co-paste figma url above
 *     - new app/src/main/ui-packages appear
 * 7. Build the project
 *     - composable generated at java (generated)
 * Now you should be able to import the component below
 * @see<a href=https://developer.android.com/develop/ui/compose/tooling/relay/convert-designs-android-studio>Relay Documentation</a>
 */

@Deprecated("Relay Plugin will sunset at 30 April 2025")
@Composable
fun RelayScreen(
    modifier: Modifier = Modifier
) {
    val currentDate = StringUtils.getCurrentDate()
    DemoScaffoldComp(
        modifier = modifier,
        title = Destinations.Relay().title
    ) {innerPadding->
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .padding(horizontal = 16.dp),
            verticalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            item {
                Text("Follow the instruction in the code to implement the relay component")
            }
//            item {
//                Text("The components below is created with relay, directly come from Figma!")
//            }
//            item {
//                ArticleItem(
//                    image = painterResource(R.drawable.tugu_jogja),
//                    title = "Hello from Relay!",
//                    date = currentDate,
//                    briefDesc = "How cool is it? no more code, just need to give it the value"
//                )
//            }
//            item {
//                ArticleItem(
//                    image = rememberAsyncImagePainter("https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?q=80&w=1379&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
//                    title = "Same as above",
//                    date = currentDate,
//                    briefDesc = "Just using url for the image"
//                )
//            }
//            item {
//                LazyRow {
//                    items(5) {
//                        ArticleSmallItem(
//                            image = painterResource(R.drawable.composedemologo),
//                            title = "Diff comp",
//                            date = currentDate
//                        )
//                    }
//                }
//            }
        }
    }
}

@Preview
@Composable
private fun RelayPreview(
    @PreviewParameter(ThemePreviewProvider::class)
    themeMode: ThemeMode
) {
    PreviewWrapperComp(
        themeMode = themeMode,
        content = {
            RelayScreen()
        }
    )
}